# Generated by Django 2.1 on 2018-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '注册用户',
                'verbose_name_plural': '注册用户',
            },
        ),
    ]
