# Generated by Django 2.1 on 2018-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivecode',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='发送的邮箱'),
        ),
        migrations.AlterField(
            model_name='emailactivecode',
            name='email_code',
            field=models.CharField(max_length=10, null=True, verbose_name='邮箱激活码'),
        ),
        migrations.AlterField(
            model_name='emailactivecode',
            name='is_delete',
            field=models.CharField(default=0, max_length=2, null=True, verbose_name='是否已经使用'),
        ),
        migrations.AlterField(
            model_name='emailactivecode',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailactivecode',
            name='send_type',
            field=models.CharField(max_length=20, null=True, verbose_name='邮件类型'),
        ),
    ]
