# Generated by Django 2.1 on 2018-12-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('summary', models.TextField(max_length=200, verbose_name='文章概要')),
                ('body', models.TextField(verbose_name='文章详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('delflag', models.CharField(default=0, max_length=2, verbose_name='删除标志')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='发表者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=50, verbose_name='栏目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文章栏目',
                'verbose_name_plural': '文章栏目',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('catory', models.CharField(max_length=50, verbose_name='分类')),
                ('doubanscore', models.CharField(max_length=50, verbose_name='豆瓣评分')),
                ('about', models.TextField(max_length=500, verbose_name='简介')),
                ('baidudiskurl', models.URLField(blank=True, verbose_name='百度下载地址')),
                ('views', models.CharField(blank=True, max_length=20, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '电子书',
                'verbose_name_plural': '电子书',
            },
        ),
        migrations.CreateModel(
            name='Bookviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_num', models.IntegerField(default=0, max_length=100, verbose_name='浏览量')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='blog.Article', verbose_name='查看的文章')),
            ],
            options={
                'verbose_name': '文章浏览量',
                'verbose_name_plural': '文章浏览量',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_del', models.CharField(default=0, max_length=4, verbose_name='删除标志')),
                ('com_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_comment', to='blog.Article', verbose_name='评论的文章')),
                ('com_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_article', to='blog.Article', verbose_name='点赞的文章')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞人')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.ArticleColumn', verbose_name='所属栏目'),
        ),
    ]
