# Generated by Django 2.1 on 2018-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '文章栏目', 'verbose_name_plural': '文章栏目'},
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateField(blank=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='update_time',
            field=models.DateField(blank=True, verbose_name='修改时间'),
        ),
    ]
