# Generated by Django 2.1 on 2018-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180812_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
