# Generated by Django 2.1 on 2018-08-21 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_del', models.CharField(default=0, max_length=4, verbose_name='删除标志')),
                ('com_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_comment', to='blog.Article', verbose_name='评论的文章')),
                ('com_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
