# Generated by Django 2.1 on 2018-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181208_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookviews',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='views_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.DeleteModel(
            name='Bookviews',
        ),
    ]
