# Generated by Django 2.1 on 2018-08-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180812_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delflag',
            field=models.CharField(default=0, max_length=2, verbose_name='删除标志'),
        ),
    ]
