# Generated by Django 2.1 on 2018-08-13 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_delflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, max_length=200, verbose_name='文章概要'),
            preserve_default=False,
        ),
    ]
