# Generated by Django 2.1 on 2018-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180820_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('catory', models.CharField(max_length=50, verbose_name='分类')),
                ('doubanscore', models.CharField(max_length=50, verbose_name='豆瓣评分')),
                ('about', models.TextField(max_length=500, verbose_name='简介')),
                ('baidudiskurl', models.URLField(verbose_name='百度下载地址')),
            ],
            options={
                'verbose_name': '电子书',
                'verbose_name_plural': '电子书',
            },
        ),
    ]
