# Generated by Django 2.1 on 2018-08-14 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.ArticleColumn', verbose_name='所属栏目'),
        ),
    ]
