# Generated by Django 2.1 on 2018-11-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='baidudiskurl',
            field=models.URLField(blank=True, verbose_name='百度下载地址'),
        ),
    ]
