# Generated by Django 2.1 on 2018-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181102_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.CharField(blank=True, max_length=20, verbose_name='浏览量'),
        ),
    ]
